version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    container_name: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq"

  database:
    image: 'mongo:4.2.2'
    hostname: "mongo"
    container_name: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=t2ee
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb:/data/db"

  nginx:
    image: "nginx:1.17.7"
    hostname: "nginx"
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/var/log/nginx/
    depends_on: 
      - api
      - webpage

  api:
    build: 
      context: api/.
      dockerfile: api.Dockerfile
    hostname: "api"
    container_name: "api"
    volumes:
      - ./api:/code
    extra_hosts:
      - "t2ee:192.168.0.133"
    ports:
      - "5000:5000"
    depends_on:
      - database
      - rabbitmq
  
  callback:
    build:
      context: api/.
      dockerfile: callback.Dockerfile
    volumes:
      - ./api:/code
    extra_hosts:
      - "t2ee:192.168.0.133"
    depends_on: 
      - database
      - rabbitmq

  webpage:
    build:
      context: webpage/.
      dockerfile: Dockerfile
    volumes:
      - ./webpage:/webpage
    hostname: "webpage"
    container_name: "webpage"
    ports:
      - "4201:4200"